# Generated by Django 3.0.4 on 2020-04-09 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBakery', '0003_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shop_address',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='product',
            name='shop_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
