# Generated by Django 3.0.4 on 2020-04-10 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBakery', '0004_auto_20200409_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('items_json', models.CharField(max_length=5000)),
                ('name', models.CharField(max_length=111)),
                ('email', models.CharField(max_length=111)),
                ('address', models.CharField(max_length=111)),
                ('address2', models.CharField(max_length=111)),
                ('phone_number', models.CharField(max_length=111)),
                ('city', models.CharField(max_length=111)),
                ('state', models.CharField(max_length=111)),
                ('zip_code', models.CharField(max_length=111)),
            ],
        ),
    ]
