# Generated by Django 3.0.4 on 2020-04-10 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBakery', '0005_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='name',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='phone_number',
            new_name='lname',
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default='', max_length=111),
        ),
    ]
