# Generated by Django 3.0.4 on 2020-04-10 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myBakery', '0006_auto_20200410_1916'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
