# Generated by Django 3.0.4 on 2020-04-10 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myBakery', '0008_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address2',
        ),
    ]
