# Generated by Django 3.0.4 on 2020-04-10 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myBakery', '0009_remove_order_address2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
