# Generated by Django 3.0.4 on 2020-04-11 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBakery', '0011_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderUpdate',
            fields=[
                ('update_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField(default='')),
                ('update_desc', models.CharField(max_length=5000)),
                ('timptamp', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
