# Generated by Django 3.0.4 on 2020-04-11 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myBakery', '0012_orderupdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderupdate',
            old_name='timptamp',
            new_name='timpstamp',
        ),
    ]
