# Generated by Django 3.0.4 on 2020-04-11 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBakery', '0013_auto_20200411_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
