# Generated by Django 3.0.4 on 2020-04-11 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myBakery', '0014_order_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderupdate',
            old_name='timpstamp',
            new_name='timestamp',
        ),
    ]
