# Generated by Django 3.0.4 on 2020-04-12 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myBakery', '0015_auto_20200411_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='amount',
        ),
    ]
