# Generated by Django 3.0.4 on 2020-04-15 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBakery', '0017_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, default='100', editable=False, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, default='100', editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', height_field='image_height', null=True, upload_to='profile_pics', width_field='image_width'),
        ),
    ]
