# Generated by Django 3.0.4 on 2020-04-15 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBakery', '0019_auto_20200415_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='profile_images/'),
        ),
    ]
