# Generated by Django 3.0.4 on 2020-04-15 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myBakery', '0021_auto_20200415_1522'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
