# Generated by Django 3.0.4 on 2020-04-15 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBakery', '0023_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image_height',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='image_width',
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
