# Generated by Django 3.0.4 on 2020-04-15 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBakery', '0024_auto_20200415_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.jpg', height_field='img_height', max_length=500, null=True, upload_to='profile_pics', width_field='img_width'),
        ),
    ]
